<!-- YouTube video's -->
<div class="row" id="youTubeVideosFrame">
    <?php foreach ($youTubeVideos AS $youTubeVideo) { ?>
        <div id="youTubeFrame<?= $youTubeVideo->getId() ?>"
             class="col-md-4 mb-2 tile youTubeFrame">
            <?php $youTubeImage = $youTubeVideo->getYouTubeImageByType('maxres'); ?>
            <?php $imageURL = (is_object($youTubeVideo->getYouTubeImageByType('maxres')) ? $youTubeVideo->getYouTubeImageByType('maxres')->getUrl() : '/img/novideofound.jpg'); ?>
            <?php if (!empty($imageURL)) { ?>
                <img data-youtubevideoid="<?= $youTubeVideo->getId(); ?>" class="img-thumbnail you-tube-pop-up" src="<?php echo $imageURL; ?>"
                     alt="<?php echo $youTubeVideo->getTitle(); ?>"/>
            <?php } ?>
            <div class="mt-2">
                <span data-youtubeid="<?php echo $youTubeVideo->getId() ?>"
                      class="removeYouTubeVideo btn btn-secondary btn-sm">
                    <i class="fas fa-trash-alt"></i>
                </span>
                <?php echo substr($youTubeVideo->getTitle(), 0, 25); ?>&hellip;
            </div>
        </div>
    <?php } ?>
</div>
<!-- Add YouTube video's -->
<div class="row mt-3 mb-3">
    <h5 class="col">Add you tube video</h5>
</div>
<div class="row">
    <div class="col-md-5">
        <label class="sr-only" for="inlineFormInputGroup">Username</label>
        <div class="input-group mb-2">
            <div class="input-group-prepend">
                <div class="input-group-text"><i class="fas fa-link"></i></div>
            </div>
            <input type="text" class="form-control" name="youtubevideolink" placeholder="YouTube link">
        </div>
        <div class="form-group has-feedback">
            <div class="input-group">
                <span class="input-group-addon"><span class="glyphicon glyphicon-link" aria-hidden="true"></span></span>
            </div>
        </div>
    </div>
    <div class="col-md-2">
        <button id="saveYouTubeVideo" type="button" class="btn btn-secondary"><i class="fas fa-plus-square"></i> Add
        </button>
    </div>
</div>

<!-- YouTube Pop-up Modal -->
<div class="modal fade bd-example-modal-lg" id="youTubePopUp" tabindex="-1" role="dialog"
     aria-labelledby="youTubePopUpLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content bg-dark">
            <div class="modal-header">
                <h5 class="modal-title" id="youTubePopUpLabel"></h5>
                <button type="button" class="close text-white" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="text-center">
                    <iframe id="youTubePopUpIframe" width="560" height="315" src="" frameborder="0"
                            allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                            allowfullscreen></iframe>
                </div>
                <div id="youTubeDescription"></div>
                <hr />
                <div>
                    <i class="fas fa-stopwatch"></i> <span id="youTubeDuration"></span>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

